/**
 * AlertService
 *
 * Service layer for the DEWS (Distressed Early Warning System) alert management.
 * Monitors prospect health thresholds, UCC filings, and payment events to generate
 * actionable alerts for portfolio managers.
 *
 * @module server/services/AlertService
 */

import crypto from 'crypto'
import { database } from '../database/connection'

/**
 * Types of alerts that can be generated by the DEWS system.
 */
export type AlertType =
  | 'health_drop'
  | 'new_ucc'
  | 'payment_missed'
  | 'score_critical'
  | 'trend_declining'

/**
 * Actions that can be taken when an alert is triggered.
 */
export type AlertAction = 'email' | 'sms' | 'webhook' | 'in_app'

/**
 * Alert severity levels.
 */
export type AlertSeverity = 'low' | 'medium' | 'high' | 'critical'

/**
 * Alert status values.
 */
export type AlertStatus = 'active' | 'acknowledged' | 'resolved' | 'dismissed'

/**
 * Rule defining when alerts should be triggered.
 */
export interface AlertRule {
  /** Unique identifier for the rule */
  id: string
  /** Organization that owns this rule */
  orgId: string
  /** Type of condition that triggers the alert */
  type: AlertType
  /** Threshold value for triggering (meaning depends on type) */
  threshold: number
  /** How to notify when triggered */
  action: AlertAction
  /** Severity level assigned to alerts from this rule */
  severity: AlertSeverity
  /** Whether this rule is active */
  enabled: boolean
  /** Optional: Only apply to specific prospects */
  prospectIds?: string[]
  /** Webhook URL if action is 'webhook' */
  webhookUrl?: string
  /** Additional configuration for the rule */
  config?: Record<string, unknown>
  /** When the rule was created */
  createdAt: string
  /** When the rule was last updated */
  updatedAt: string
}

/**
 * Alert entity representing a triggered warning.
 */
export interface Alert {
  /** Unique identifier */
  id: string
  /** Organization ID */
  orgId: string
  /** Rule that triggered this alert (null if ad-hoc) */
  ruleId?: string
  /** Prospect that triggered the alert */
  prospectId: string
  /** Type of alert */
  type: AlertType
  /** Severity level */
  severity: AlertSeverity
  /** Current status */
  status: AlertStatus
  /** Alert title */
  title: string
  /** Detailed message */
  message: string
  /** Additional context data */
  data: Record<string, unknown>
  /** When the alert was created */
  createdAt: string
  /** When the alert was acknowledged */
  acknowledgedAt?: string
  /** User who acknowledged */
  acknowledgedBy?: string
  /** When the alert was resolved */
  resolvedAt?: string
  /** User who resolved */
  resolvedBy?: string
  /** Resolution notes */
  resolutionNotes?: string
}

/**
 * Parameters for creating a new alert.
 */
export interface CreateAlertParams {
  orgId: string
  prospectId: string
  type: AlertType
  severity?: AlertSeverity
  title: string
  message: string
  data?: Record<string, unknown>
  ruleId?: string
}

/**
 * Parameters for listing alerts.
 */
export interface ListAlertsParams {
  orgId: string
  status?: AlertStatus | AlertStatus[]
  type?: AlertType
  severity?: AlertSeverity
  prospectId?: string
  limit?: number
  offset?: number
}

/**
 * Health threshold check result.
 */
export interface HealthCheckResult {
  prospectId: string
  currentScore: number
  previousScore?: number
  scoreDrop?: number
  triggeredRules: AlertRule[]
  alertsCreated: Alert[]
}

/**
 * Raw `alerts` table row shape (migration 020). snake_case columns, JSONB data.
 */
interface AlertRow {
  id: string
  org_id: string
  rule_id: string | null
  prospect_id: string
  type: AlertType
  severity: AlertSeverity
  status: AlertStatus
  title: string
  message: string
  data: Record<string, unknown> | null
  created_at: string | Date
  acknowledged_at: string | Date | null
  acknowledged_by: string | null
  resolved_at: string | Date | null
  resolved_by: string | null
  resolution_notes: string | null
}

/**
 * Raw `alert_rules` table row shape (migration 020).
 */
interface AlertRuleRow {
  id: string
  org_id: string
  type: AlertType
  threshold: number | string
  action: AlertAction
  severity: AlertSeverity
  enabled: boolean
  prospect_ids: string[] | null
  webhook_url: string | null
  config: Record<string, unknown> | null
  created_at: string | Date
  updated_at: string | Date
}

function toIso(value: string | Date | null | undefined): string | undefined {
  if (value == null) return undefined
  return value instanceof Date ? value.toISOString() : value
}

function mapAlertRow(row: AlertRow): Alert {
  return {
    id: row.id,
    orgId: row.org_id,
    ruleId: row.rule_id ?? undefined,
    prospectId: row.prospect_id,
    type: row.type,
    severity: row.severity,
    status: row.status,
    title: row.title,
    message: row.message,
    data: row.data ?? {},
    createdAt: toIso(row.created_at) ?? new Date().toISOString(),
    acknowledgedAt: toIso(row.acknowledged_at),
    acknowledgedBy: row.acknowledged_by ?? undefined,
    resolvedAt: toIso(row.resolved_at),
    resolvedBy: row.resolved_by ?? undefined,
    resolutionNotes: row.resolution_notes ?? undefined
  }
}

function mapRuleRow(row: AlertRuleRow): AlertRule {
  return {
    id: row.id,
    orgId: row.org_id,
    type: row.type,
    threshold: Number(row.threshold),
    action: row.action,
    severity: row.severity,
    enabled: row.enabled,
    prospectIds: row.prospect_ids ?? undefined,
    webhookUrl: row.webhook_url ?? undefined,
    config: row.config ?? undefined,
    createdAt: toIso(row.created_at) ?? new Date().toISOString(),
    updatedAt: toIso(row.updated_at) ?? new Date().toISOString()
  }
}

/**
 * Service for managing DEWS (Distressed Early Warning System) alerts.
 *
 * Provides methods for:
 * - Checking health thresholds and triggering alerts
 * - Creating and managing alerts
 * - Configuring alert rules
 * - Retrieving alert history
 *
 * @example
 * ```typescript
 * const service = new AlertService()
 *
 * // Check health thresholds for a prospect
 * const alerts = await service.checkHealthThresholds('prospect-123')
 *
 * // Get active alerts for an organization
 * const activeAlerts = await service.getActiveAlerts('org-456')
 *
 * // Acknowledge an alert
 * await service.acknowledgeAlert('alert-789', 'user-001')
 * ```
 */
export class AlertService {
  /**
   * Check health thresholds for a prospect and generate alerts if needed.
   *
   * Evaluates all enabled alert rules for the organization and creates
   * alerts for any triggered conditions.
   *
   * @param prospectId - The prospect's unique identifier
   * @returns Array of alerts generated from threshold checks
   */
  async checkHealthThresholds(prospectId: string): Promise<Alert[]> {
    // Get the prospect's current and previous health scores
    const healthQuery = `
      SELECT
        p.id as prospect_id,
        p.org_id,
        p.company_name,
        h1.health_score as current_score,
        h1.health_grade as current_grade,
        h2.health_score as previous_score,
        h2.health_grade as previous_grade
      FROM prospects p
      LEFT JOIN LATERAL (
        SELECT health_score, health_grade
        FROM portfolio_health_history
        WHERE prospect_id = p.id
        ORDER BY recorded_at DESC
        LIMIT 1
      ) h1 ON true
      LEFT JOIN LATERAL (
        SELECT health_score, health_grade
        FROM portfolio_health_history
        WHERE prospect_id = p.id
        ORDER BY recorded_at DESC
        LIMIT 1 OFFSET 1
      ) h2 ON true
      WHERE p.id = $1
    `

    const results = await database.query<{
      prospect_id: string
      org_id: string
      company_name: string
      current_score: number | null
      current_grade: string | null
      previous_score: number | null
      previous_grade: string | null
    }>(healthQuery, [prospectId])

    if (results.length === 0) {
      return []
    }

    const prospect = results[0]

    // If no health history, nothing to check
    if (prospect.current_score === null) {
      return []
    }

    // Get enabled rules for this organization
    const rules = await this.getEnabledRules(prospect.org_id)

    const alerts: Alert[] = []

    for (const rule of rules) {
      // Check if rule applies to this prospect
      if (rule.prospectIds && rule.prospectIds.length > 0) {
        if (!rule.prospectIds.includes(prospectId)) {
          continue
        }
      }

      let shouldAlert = false
      let alertTitle = ''
      let alertMessage = ''
      const alertData: Record<string, unknown> = {
        currentScore: prospect.current_score,
        previousScore: prospect.previous_score,
        threshold: rule.threshold
      }

      switch (rule.type) {
        case 'health_drop':
          // Check if health score dropped by more than threshold
          if (prospect.previous_score !== null) {
            const drop = prospect.previous_score - prospect.current_score
            if (drop >= rule.threshold) {
              shouldAlert = true
              alertTitle = `Health score dropped by ${drop} points`
              alertMessage = `${prospect.company_name}'s health score dropped from ${prospect.previous_score} to ${prospect.current_score}`
              alertData.scoreDrop = drop
            }
          }
          break

        case 'score_critical':
          // Check if score is below critical threshold
          if (prospect.current_score <= rule.threshold) {
            shouldAlert = true
            alertTitle = `Health score critically low: ${prospect.current_score}`
            alertMessage = `${prospect.company_name}'s health score (${prospect.current_score}) is below the critical threshold of ${rule.threshold}`
          }
          break

        case 'trend_declining':
          // Check for sustained declining trend (would need more history in production)
          if (
            prospect.previous_score !== null &&
            prospect.current_score < prospect.previous_score
          ) {
            const drop = prospect.previous_score - prospect.current_score
            if (drop >= rule.threshold) {
              shouldAlert = true
              alertTitle = `Declining health trend detected`
              alertMessage = `${prospect.company_name} shows a declining health trend (${prospect.previous_score} -> ${prospect.current_score})`
            }
          }
          break
      }

      if (shouldAlert) {
        const alert = await this.createAlert({
          orgId: prospect.org_id,
          prospectId,
          type: rule.type,
          severity: rule.severity,
          title: alertTitle,
          message: alertMessage,
          data: alertData,
          ruleId: rule.id
        })
        alerts.push(alert)

        // Execute the action (email, SMS, webhook)
        await this.executeAlertAction(alert, rule)
      }
    }

    return alerts
  }

  /**
   * Create a new alert.
   *
   * @param params - Alert creation parameters
   * @returns The created alert
   */
  async createAlert(params: CreateAlertParams): Promise<Alert> {
    const {
      orgId,
      prospectId,
      type,
      severity = 'medium',
      title,
      message,
      data = {},
      ruleId
    } = params

    // Persist to the `alerts` table (migration 020). The DB generates the id and
    // created_at; the inserted row is mapped back to the Alert shape.
    const rows = await database.query<AlertRow>(
      `INSERT INTO alerts (org_id, rule_id, prospect_id, type, severity, status, title, message, data)
       VALUES ($1, $2, $3, $4, $5, 'active', $6, $7, $8::jsonb)
       RETURNING *`,
      [orgId, ruleId ?? null, prospectId, type, severity, title, message, JSON.stringify(data)]
    )

    return mapAlertRow(rows[0])
  }

  /**
   * Get all active alerts for an organization.
   *
   * @param orgId - The organization's unique identifier
   * @returns Array of active alerts
   */
  async getActiveAlerts(orgId: string): Promise<Alert[]> {
    const rows = await database.query<AlertRow>(
      `SELECT *
       FROM alerts
       WHERE org_id = $1 AND status = 'active'
       ORDER BY
         CASE severity WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 ELSE 4 END,
         created_at DESC`,
      [orgId]
    )
    return rows.map(mapAlertRow)
  }

  /**
   * Acknowledge an alert.
   *
   * @param alertId - The alert's unique identifier
   * @param userId - The user acknowledging the alert
   */
  async acknowledgeAlert(alertId: string, userId?: string): Promise<void> {
    await database.query(
      `UPDATE alerts
         SET status = 'acknowledged',
             acknowledged_at = NOW(),
             acknowledged_by = $2
       WHERE id = $1 AND status = 'active'`,
      [alertId, userId ?? null]
    )
  }

  /**
   * Resolve an alert with optional notes.
   *
   * @param alertId - The alert's unique identifier
   * @param userId - The user resolving the alert
   * @param notes - Optional resolution notes
   */
  async resolveAlert(alertId: string, userId?: string, notes?: string): Promise<void> {
    await database.query(
      `UPDATE alerts
         SET status = 'resolved',
             resolved_at = NOW(),
             resolved_by = $2,
             resolution_notes = $3
       WHERE id = $1`,
      [alertId, userId ?? null, notes ?? null]
    )
  }

  /**
   * Dismiss an alert (mark as not requiring action).
   *
   * @param alertId - The alert's unique identifier
   * @param userId - The user dismissing the alert
   */
  async dismissAlert(alertId: string, userId?: string): Promise<void> {
    await database.query(
      `UPDATE alerts
         SET status = 'dismissed',
             resolved_at = NOW(),
             resolved_by = $2,
             resolution_notes = COALESCE(resolution_notes, 'Dismissed')
       WHERE id = $1`,
      [alertId, userId ?? null]
    )
  }

  /**
   * Get alert history for a prospect.
   *
   * @param prospectId - The prospect's unique identifier
   * @param limit - Maximum number of alerts to return (default 50)
   * @returns Array of historical alerts
   */
  async getAlertHistory(prospectId: string, limit: number = 50): Promise<Alert[]> {
    const rows = await database.query<AlertRow>(
      `SELECT *
       FROM alerts
       WHERE prospect_id = $1
       ORDER BY created_at DESC
       LIMIT $2`,
      [prospectId, limit]
    )
    return rows.map(mapAlertRow)
  }

  /**
   * List alerts with filtering and pagination.
   *
   * @param params - List parameters
   * @returns Paginated array of alerts
   */
  async listAlerts(params: ListAlertsParams): Promise<{ alerts: Alert[]; total: number }> {
    const { orgId, status, type, severity, prospectId, limit = 50, offset = 0 } = params

    const conditions: string[] = ['org_id = $1']
    const values: unknown[] = [orgId]

    if (status !== undefined) {
      const statuses = Array.isArray(status) ? status : [status]
      values.push(statuses)
      conditions.push(`status = ANY($${values.length})`)
    }
    if (type !== undefined) {
      values.push(type)
      conditions.push(`type = $${values.length}`)
    }
    if (severity !== undefined) {
      values.push(severity)
      conditions.push(`severity = $${values.length}`)
    }
    if (prospectId !== undefined) {
      values.push(prospectId)
      conditions.push(`prospect_id = $${values.length}`)
    }

    const where = conditions.join(' AND ')

    const countRows = await database.query<{ total: string | number }>(
      `SELECT COUNT(*)::int AS total FROM alerts WHERE ${where}`,
      values
    )
    const total = Number(countRows[0]?.total ?? 0)

    const limitParam = values.length + 1
    const offsetParam = values.length + 2
    const rows = await database.query<AlertRow>(
      `SELECT *
       FROM alerts
       WHERE ${where}
       ORDER BY created_at DESC
       LIMIT $${limitParam} OFFSET $${offsetParam}`,
      [...values, limit, offset]
    )

    return { alerts: rows.map(mapAlertRow), total }
  }

  /**
   * Create or update an alert rule.
   *
   * @param rule - The rule to create or update
   * @returns The saved rule
   */
  async saveRule(
    rule: Omit<AlertRule, 'createdAt' | 'updatedAt'> & { id?: string }
  ): Promise<AlertRule> {
    // Upsert: INSERT a new rule (DB-generated id) or UPDATE in place when an id
    // is supplied. ON CONFLICT keeps created_at and bumps updated_at.
    const id = rule.id ?? crypto.randomUUID()
    const prospectIds = rule.prospectIds && rule.prospectIds.length > 0 ? rule.prospectIds : null

    const rows = await database.query<AlertRuleRow>(
      `INSERT INTO alert_rules
         (id, org_id, type, threshold, action, severity, enabled, prospect_ids, webhook_url, config)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10::jsonb)
       ON CONFLICT (id) DO UPDATE SET
         type = EXCLUDED.type,
         threshold = EXCLUDED.threshold,
         action = EXCLUDED.action,
         severity = EXCLUDED.severity,
         enabled = EXCLUDED.enabled,
         prospect_ids = EXCLUDED.prospect_ids,
         webhook_url = EXCLUDED.webhook_url,
         config = EXCLUDED.config,
         updated_at = NOW()
       RETURNING *`,
      [
        id,
        rule.orgId,
        rule.type,
        rule.threshold,
        rule.action,
        rule.severity,
        rule.enabled,
        prospectIds,
        rule.webhookUrl ?? null,
        rule.config ? JSON.stringify(rule.config) : null
      ]
    )

    return mapRuleRow(rows[0])
  }

  /**
   * Get enabled rules for an organization.
   *
   * @param orgId - The organization's unique identifier
   * @returns Array of enabled alert rules
   */
  async getEnabledRules(orgId: string): Promise<AlertRule[]> {
    const rows = await database.query<AlertRuleRow>(
      `SELECT *
       FROM alert_rules
       WHERE org_id = $1 AND enabled = true
       ORDER BY type, threshold`,
      [orgId]
    )
    return rows.map(mapRuleRow)
  }

  /**
   * Delete an alert rule.
   *
   * @param ruleId - The rule's unique identifier
   */
  async deleteRule(ruleId: string): Promise<void> {
    await database.query('DELETE FROM alert_rules WHERE id = $1', [ruleId])
  }

  /**
   * Configure alert rules for an organization.
   *
   * Bulk update/replace alert rules for an organization. This method
   * replaces all existing rules with the provided set.
   *
   * @param orgId - The organization's unique identifier
   * @param rules - Array of alert rules to configure
   * @returns The configured rules with generated IDs
   */
  async configureAlertRules(
    orgId: string,
    rules: Array<Omit<AlertRule, 'id' | 'orgId' | 'createdAt' | 'updatedAt'>>
  ): Promise<AlertRule[]> {
    // Transactionally replace the org's rule set: delete existing, insert new.
    const client = await database.getPoolClient()
    const configured: AlertRule[] = []
    try {
      await client.query('BEGIN')
      await client.query('DELETE FROM alert_rules WHERE org_id = $1', [orgId])

      for (const rule of rules) {
        const prospectIds =
          rule.prospectIds && rule.prospectIds.length > 0 ? rule.prospectIds : null
        const result = await client.query(
          `INSERT INTO alert_rules
             (org_id, type, threshold, action, severity, enabled, prospect_ids, webhook_url, config)
           VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9::jsonb)
           RETURNING *`,
          [
            orgId,
            rule.type,
            rule.threshold,
            rule.action,
            rule.severity,
            rule.enabled,
            prospectIds,
            rule.webhookUrl ?? null,
            rule.config ? JSON.stringify(rule.config) : null
          ]
        )
        configured.push(mapRuleRow(result.rows[0] as AlertRuleRow))
      }

      await client.query('COMMIT')
    } catch (error) {
      await client.query('ROLLBACK')
      throw error
    } finally {
      client.release()
    }

    return configured
  }

  /**
   * Execute the alert action (send notification).
   *
   * @param alert - The alert to notify about
   * @param rule - The rule that triggered the alert
   */
  private async executeAlertAction(alert: Alert, rule: AlertRule): Promise<void> {
    switch (rule.action) {
      case 'email':
        console.log(`[AlertService] Email transport is not wired for alert: ${alert.title}`)
        // In production: await sendGridClient.send({ ... })
        break

      case 'sms':
        console.log(`[AlertService] SMS transport is not wired for alert: ${alert.title}`)
        // In production: await twilioClient.sendSms({ ... })
        break

      case 'webhook':
        if (rule.webhookUrl) {
          console.log(
            `[AlertService] Webhook transport is not wired for ${rule.webhookUrl} on alert: ${alert.title}`
          )
          // In production: await fetch(rule.webhookUrl, { method: 'POST', body: JSON.stringify(alert) })
        }
        break

      case 'in_app':
        console.log(`[AlertService] In-app notification for alert: ${alert.title}`)
        // In-app notifications are handled by the frontend polling getActiveAlerts
        break
    }
  }

  /**
   * Record a new health score and check thresholds.
   *
   * Convenience method that records a health score and then checks
   * if any alerts should be triggered.
   *
   * @param prospectId - The prospect's unique identifier
   * @param score - The health score (0-100)
   * @param factors - Contributing factors
   * @returns Any alerts that were generated
   */
  async recordHealthAndCheck(
    prospectId: string,
    score: number,
    factors?: Record<string, unknown>
  ): Promise<Alert[]> {
    // Record the health score
    const insertQuery = `
      INSERT INTO portfolio_health_history (prospect_id, health_score, factors, source)
      VALUES ($1, $2, $3, 'system')
      RETURNING id
    `

    try {
      await database.query(insertQuery, [
        prospectId,
        score,
        factors ? JSON.stringify(factors) : null
      ])
      console.log(`[AlertService] Recorded health score ${score} for prospect ${prospectId}`)
    } catch (error) {
      console.error(`[AlertService] Failed to record health score:`, error)
      // Continue to check thresholds even if recording failed
    }

    // Check if any alerts should be triggered
    return this.checkHealthThresholds(prospectId)
  }
}

/**
 * Default AlertService instance
 */
export const alertService = new AlertService()
